-- ============================================================
-- LOADSTRAT — biblioteca padrão de exercícios (owner_id = NULL)
-- Lida por todos os autenticados; escrita só por migration.
-- Base: a lista do protótipo, ampliada.
-- ============================================================

insert into public.exercises (owner_id, nome, grupo, padrao, categoria) values
-- Peito
(null,'Supino reto barra','Peito','Empurrar','forca'),
(null,'Supino inclinado halteres','Peito','Empurrar','forca'),
(null,'Supino declinado','Peito','Empurrar','forca'),
(null,'Crucifixo halteres','Peito','Empurrar','forca'),
(null,'Crossover na polia','Peito','Empurrar','forca'),
(null,'Flexão de braço','Peito','Empurrar','forca'),
(null,'Paralelas (dips)','Peito','Empurrar','forca'),
-- Ombro
(null,'Desenvolvimento militar','Ombro','Empurrar','forca'),
(null,'Desenvolvimento halteres','Ombro','Empurrar','forca'),
(null,'Push press','Ombro','Empurrar','forca'),
(null,'Elevação lateral','Ombro','Empurrar','forca'),
(null,'Elevação frontal','Ombro','Empurrar','forca'),
(null,'Face pull','Ombro','Puxar','forca'),
(null,'Crucifixo inverso','Ombro','Puxar','forca'),
(null,'Dislocate de ombro','Ombro','Mobilidade','tempo'),
-- Costas
(null,'Barra fixa','Costas','Puxar','forca'),
(null,'Puxada frente','Costas','Puxar','forca'),
(null,'Remada curvada','Costas','Puxar','forca'),
(null,'Remada baixa','Costas','Puxar','forca'),
(null,'Remada unilateral (serrote)','Costas','Puxar','forca'),
(null,'Pull-over','Costas','Puxar','forca'),
(null,'Cat-camel torácica','Costas','Mobilidade','tempo'),
-- Braços
(null,'Rosca direta','Braços','Puxar','forca'),
(null,'Rosca martelo','Braços','Puxar','forca'),
(null,'Rosca scott','Braços','Puxar','forca'),
(null,'Tríceps corda','Braços','Empurrar','forca'),
(null,'Tríceps testa','Braços','Empurrar','forca'),
(null,'Tríceps francês','Braços','Empurrar','forca'),
-- Pernas
(null,'Agachamento livre','Pernas','Agachar','forca'),
(null,'Agachamento frontal','Pernas','Agachar','forca'),
(null,'Agachamento goblet','Pernas','Agachar','forca'),
(null,'Leg press 45°','Pernas','Agachar','forca'),
(null,'Hack machine','Pernas','Agachar','forca'),
(null,'Cadeira extensora','Pernas','Agachar','forca'),
(null,'Mesa flexora','Pernas','Dobradiça','forca'),
(null,'Levantamento terra','Pernas','Dobradiça','forca'),
(null,'Terra romeno','Pernas','Dobradiça','forca'),
(null,'Stiff','Pernas','Dobradiça','forca'),
(null,'Good morning','Pernas','Dobradiça','forca'),
(null,'Afundo (lunge)','Pernas','Avanço','forca'),
(null,'Búlgaro','Pernas','Avanço','forca'),
(null,'Step-up','Pernas','Avanço','forca'),
(null,'Passada (walking lunge)','Pernas','Avanço','forca'),
(null,'Panturrilha em pé','Pernas','Locomoção','forca'),
(null,'Panturrilha sentado','Pernas','Locomoção','forca'),
(null,'Box jump','Pernas','Arremesso','forca'),
(null,'Power clean','Pernas','Arremesso','forca'),
(null,'Agachamento com salto','Pernas','Arremesso','forca'),
(null,'Mobilidade 90/90','Pernas','Mobilidade','tempo'),
-- Glúteo
(null,'Hip thrust','Glúteo','Dobradiça','forca'),
(null,'Elevação pélvica','Glúteo','Dobradiça','forca'),
(null,'Kettlebell swing','Glúteo','Arremesso','forca'),
(null,'Abdução na máquina','Glúteo','Rotação','forca'),
(null,'Coice na polia','Glúteo','Dobradiça','forca'),
(null,'Ponte unilateral','Glúteo','Dobradiça','forca'),
-- Core
(null,'Prancha','Core','Anti-rotação','tempo'),
(null,'Prancha lateral','Core','Anti-rotação','tempo'),
(null,'Pallof press','Core','Anti-rotação','forca'),
(null,'Dead bug','Core','Anti-rotação','forca'),
(null,'Bird dog','Core','Anti-rotação','forca'),
(null,'Lenhador na polia','Core','Rotação','forca'),
(null,'Landmine rotation','Core','Rotação','forca'),
(null,'Med ball rotacional','Core','Rotação','forca'),
(null,'Slam ball','Core','Arremesso','forca'),
(null,'Farmer walk','Core','Locomoção','tempo'),
(null,'Abdominal infra','Core','Anti-rotação','forca'),
(null,'Roda abdominal','Core','Anti-rotação','forca'),
-- Cardio
(null,'Esteira','Cardio','Locomoção','tempo'),
(null,'Bike','Cardio','Locomoção','tempo'),
(null,'Elíptico','Cardio','Locomoção','tempo'),
(null,'Remo ergômetro','Cardio','Locomoção','tempo'),
(null,'HIIT esteira','Cardio','Locomoção','tempo'),
(null,'Corrida de rua','Cardio','Locomoção','tempo'),
(null,'Pular corda','Cardio','Locomoção','tempo'),
(null,'Escada (stairmaster)','Cardio','Locomoção','tempo');
